export const Actions = {
  START: "start",
  TILE: "tile",
  UNDO: "undo",
  SHOW_HINT: "show-hint",
  RESET: "reset",
  NEXT: "next",
  BACK: "back",
  SET_LOCALE: "set-locale",
  HISTORY: "history",
  HISTORY_BACK: "history-back",
  HISTORY_PLAY: "history-play",
  COPY_PERMALINK: "copy-permalink",
  INVALID_PERMALINK_BACK: "invalid-permalink-back",
};
