export const styles = {
  container: {
    minHeight: "100vh",
    background: "#f5edd6",
    backgroundImage:
      "repeating-linear-gradient(0deg, transparent, transparent 39px, #e8dcc3 39px, #e8dcc3 40px), repeating-linear-gradient(90deg, transparent, transparent 39px, #e8dcc3 39px, #e8dcc3 40px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "'Noto Serif JP', 'Hiragino Mincho ProN', 'Yu Mincho', serif",
    color: "#2a2016",
    padding: "20px",
    boxSizing: "border-box",
  },
  titleScreen: {
    textAlign: "center",
    maxWidth: "420px",
  },
  titleTopRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: "10px",
  },
  titleKanji: {
    fontSize: "96px",
    fontWeight: "900",
    lineHeight: "1",
    color: "#2a2016",
    textShadow: "3px 3px 0 #d4c4a0",
    marginBottom: "8px",
  },
  titleMain: {
    fontSize: "32px",
    fontWeight: "700",
    margin: "0 0 4px",
    letterSpacing: "8px",
  },
  titleSub: {
    fontSize: "14px",
    color: "#7a6b52",
    margin: "0 0 36px",
    letterSpacing: "4px",
  },
  diffGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
    marginBottom: "32px",
  },
  diffButton: {
    background: "transparent",
    border: "2px solid #2a2016",
    color: "#2a2016",
    padding: "16px 12px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s",
  },
  diffKanji: {
    fontSize: "28px",
    fontWeight: "700",
  },
  diffLabel: {
    fontSize: "13px",
    letterSpacing: "2px",
  },
  ruleText: {
    fontSize: "13px",
    lineHeight: "1.8",
    color: "#7a6b52",
  },
  gameScreen: {
    width: "100%",
    maxWidth: "520px",
    position: "relative",
    alignSelf: "flex-start",
  },
  header: {
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    marginBottom: "24px",
    gap: "12px",
    background: "#efe4c8",
    padding: "10px 16px",
    borderRadius: "4px",
    position: "sticky",
    top: "0",
    zIndex: "5",
  },
  backButton: {
    background: "none",
    border: "none",
    fontFamily: "inherit",
    fontSize: "14px",
    color: "#7a6b52",
    cursor: "pointer",
    padding: "4px 0",
    justifySelf: "start",
    transition: "color 0.2s",
  },
  headerCenter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "2px",
  },
  headerDiff: {
    fontSize: "18px",
    fontWeight: "700",
    letterSpacing: "4px",
  },
  headerNum: {
    fontSize: "12px",
    color: "#7a6b52",
  },
  headerRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifySelf: "end",
    gap: "8px",
  },
  moveLabel: {
    fontSize: "15px",
    fontWeight: "700",
    fontVariantNumeric: "tabular-nums",
  },
  localeSwitch: {
    display: "inline-flex",
    border: "1px solid #7a6b52",
    borderRadius: "999px",
    overflow: "hidden",
    background: "#efe4c8",
  },
  localeButton: {
    background: "transparent",
    border: "none",
    color: "#6d5f49",
    padding: "5px 10px",
    fontFamily: "inherit",
    fontSize: "12px",
    cursor: "pointer",
    lineHeight: "1.1",
  },
  localeButtonActive: {
    background: "#2a2016",
    color: "#e8d5b5",
  },
  boardWrapper: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: "24px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  board: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "4px",
    background: "#2a2016",
    padding: "4px",
    borderRadius: "2px",
    width: "264px",
    height: "264px",
    flexShrink: "0",
  },
  emptyCell: {
    background: "#3d3225",
    borderRadius: "1px",
  },
  tile: {
    background: "#e8d5b5",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "1px",
    transition: "all 0.12s ease",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  tileMovable: {
    background: "#f0e4c8",
    boxShadow: "inset 0 0 0 2px #b89e6e",
  },
  tileAnimating: {
    transform: "scale(0.93)",
  },
  tileHinted: {
    animation: "flashHint 2s ease-out forwards",
  },
  tileNumber: {
    fontSize: "32px",
    fontWeight: "700",
    color: "#2a2016",
  },
  goalSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
  },
  goalLabel: {
    fontSize: "11px",
    color: "#7a6b52",
    letterSpacing: "2px",
  },
  goalGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "2px",
    background: "#c4b89a",
    padding: "2px",
    borderRadius: "2px",
    width: "84px",
    height: "84px",
  },
  goalTile: {
    background: "#e8d5b5",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: "600",
    color: "#5a4d3a",
    borderRadius: "1px",
  },
  goalEmpty: {
    background: "#b8ab8e",
    borderRadius: "1px",
  },
  controls: {
    display: "flex",
    justifyContent: "center",
    gap: "12px",
    flexWrap: "wrap",
    marginBottom: "16px",
  },
  controlBtn: {
    background: "none",
    border: "1.5px solid #7a6b52",
    color: "#7a6b52",
    padding: "8px 20px",
    fontFamily: "inherit",
    fontSize: "13px",
    cursor: "pointer",
    transition: "opacity 0.2s",
    letterSpacing: "1px",
  },
  permalinkStatus: {
    textAlign: "center",
    fontSize: "12px",
    color: "#7a6b52",
    minHeight: "18px",
    margin: "0 0 12px",
  },
  resultOverlay: {
    position: "absolute",
    inset: "0",
    background: "rgba(245, 237, 214, 0.85)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: "10",
    backdropFilter: "blur(2px)",
  },
  resultCard: {
    background: "#f5edd6",
    border: "3px solid",
    padding: "36px 48px",
    textAlign: "center",
  },
  resultKanji: {
    fontSize: "56px",
    fontWeight: "900",
    color: "#4a7c59",
    lineHeight: "1",
    marginBottom: "8px",
  },
  resultText: {
    fontSize: "15px",
    color: "#5a4d3a",
    margin: "0 0 24px",
  },
  resultButtons: {
    display: "flex",
    gap: "12px",
    justifyContent: "center",
  },
  resultBtn: {
    background: "#2a2016",
    color: "#e8d5b5",
    border: "none",
    padding: "10px 24px",
    fontFamily: "inherit",
    fontSize: "14px",
    cursor: "pointer",
    letterSpacing: "2px",
  },
  hint: {
    textAlign: "center",
    fontSize: "11px",
    color: "#a89b80",
    margin: "0",
  },
  historyButton: {
    background: "transparent",
    border: "1.5px solid #7a6b52",
    color: "#7a6b52",
    padding: "10px 24px",
    fontFamily: "inherit",
    fontSize: "14px",
    cursor: "pointer",
    letterSpacing: "2px",
    marginBottom: "24px",
    transition: "all 0.2s",
  },
  historyScreen: {
    width: "100%",
    maxWidth: "520px",
    alignSelf: "flex-start",
  },
  historyHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    background: "#efe4c8",
    padding: "10px 16px",
    borderRadius: "4px",
  },
  historyBackButton: {
    background: "none",
    border: "none",
    fontFamily: "inherit",
    fontSize: "14px",
    color: "#7a6b52",
    cursor: "pointer",
    padding: "4px 0",
    transition: "color 0.2s",
  },
  historyTitle: {
    fontSize: "18px",
    fontWeight: "700",
    letterSpacing: "4px",
  },
  historyList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  historyItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    background: "#efe4c8",
    padding: "10px 16px",
    borderRadius: "4px",
    fontSize: "14px",
    cursor: "pointer",
  },
  historyResult: {
    fontSize: "20px",
    fontWeight: "700",
    width: "28px",
    textAlign: "center",
    flexShrink: "0",
  },
  historyDetails: {
    flex: "1",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  historyMoves: {
    fontSize: "14px",
    fontWeight: "600",
  },
  historyMeta: {
    fontSize: "12px",
    color: "#7a6b52",
  },
  historyEmpty: {
    textAlign: "center",
    color: "#7a6b52",
    fontSize: "14px",
    padding: "40px 0",
  },
  invalidScreen: {
    width: "100%",
    maxWidth: "420px",
    textAlign: "center",
    background: "#efe4c8",
    borderRadius: "4px",
    padding: "40px 28px",
    boxSizing: "border-box",
  },
  invalidTitle: {
    fontSize: "28px",
    fontWeight: "700",
    margin: "0 0 12px",
    letterSpacing: "2px",
  },
  invalidText: {
    fontSize: "14px",
    color: "#7a6b52",
    lineHeight: "1.8",
    margin: "0 0 24px",
  },
  invalidButton: {
    background: "#2a2016",
    color: "#e8d5b5",
    border: "none",
    padding: "10px 24px",
    fontFamily: "inherit",
    fontSize: "14px",
    cursor: "pointer",
    letterSpacing: "2px",
  },
};

export function applyStyles(element, styleObject) {
  Object.assign(element.style, styleObject);
}

export function withHoverStyle(element, hoverStyle, baseStyle) {
  element.addEventListener("mouseenter", () => {
    Object.assign(element.style, hoverStyle);
  });
  element.addEventListener("mouseleave", () => {
    Object.assign(element.style, baseStyle);
  });
}

const styleTag = document.createElement("style");
styleTag.textContent = `
@keyframes flashHint {
  0% { background: #d4e0ce; box-shadow: inset 0 0 0 3px #4a7c59; transform: scale(0.95); }
  10% { transform: scale(1); }
  70% { background: #d4e0ce; box-shadow: inset 0 0 0 3px #4a7c59; }
  100% { background: #f0e4c8; box-shadow: inset 0 0 0 2px #b89e6e; }
}
`;
document.head.appendChild(styleTag);
